// Generated by scripts/gen-clients.mjs from scope_trust_policy.wasm (sha256 d1be4db42ec0c71e31b69871b124e673c8d842283b678583742094be0232ccd3).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = 'd1be4db42ec0c71e31b69871b124e673c8d842283b678583742094be0232ccd3';
