// Generated by scripts/gen-clients.mjs from scope_trust_policy.wasm (sha256 d1be4db42ec0c71e31b69871b124e673c8d842283b678583742094be0232ccd3).
// Do not edit: rebuild the contract and run the script again.
import {Address, xdr} from '@stellar/stellar-sdk';
import { Buffer } from 'buffer';

    /**
 * Event: Installed
 */
export interface InstalledEvent {
  name: "Installed";
  data: {
    smart_account: string;
    context_rule_id?: number;
    params?: TrustPolicyParams;
  };
}

/**
 * Event: Uninstalled
 */
export interface UninstalledEvent {
  name: "Uninstalled";
  data: {
    smart_account: string;
    context_rule_id?: number;
  };
}

/**
 * Error Enum: TrustPolicyError
 */
export const TrustPolicyError = {
  /**
   * The destination is not trusted by enough attesters.
   */
  1 : { message: "NotTrusted" },
  2 : { message: "NotInstalled" },
  3 : { message: "InvalidParams" },
  4 : { message: "AlreadyInstalled" },
  /**
   * No signer of the rule authenticated. OpenZeppelin smart accounts defer
   * signer checks to policies when a rule has any, so this policy refuses
   * to authorize anything without at least one authenticated signer.
   */
  5 : { message: "NoSigner" }
}

/**
 * Struct: TrustPolicyParams
 */
export interface TrustPolicyParams {
  attesters: Array<string>;
  max_unverified: bigint;
  min_score: number;
  quorum: number;
  registry: string;
}

/**
 * Contract executable used for creating a new contract and used in
 * `CreateContractHostFnContext`.
 */
 export type ContractExecutable =
  /**
   * Executable specified by the contract instance as a specific Wasm contract code entry identified by its Wasm sha256 hash.
   */
  { tag: "Wasm"; values: readonly [Buffer] } |
  /**
   * Executable reference via a persistent storage entry owned by this contract or another contract.
   */
  { tag: "ExternalRef"; values: readonly [ContractExecutableRef] };

/**
 * Executable referenced via a persistent storage entry owned by a contract,
 * either this contract or another contract.
 *
 * The persistent storage entry owned by the `owner` has the `tag` as its key.
 */
export interface ContractExecutableRef {
  owner: string;
  tag: string;
}

/**
 * Context of a single authorized call performed by an address.
 *
 * Custom account contracts that implement `__check_auth` special function
 * receive a list of `Context` values corresponding to all the calls that
 * need to be authorized.
 */
 export type Context =
  /**
   * Contract invocation.
   */
  { tag: "Contract"; values: readonly [ContractContext] } |
  /**
   * Contract that has a constructor with no arguments is created.
   */
  { tag: "CreateContractHostFn"; values: readonly [CreateContractHostFnContext] } |
  /**
   * Contract that has a constructor with 1 or more arguments is created.
   */
  { tag: "CreateContractWithCtorHostFn"; values: readonly [CreateContractWithConstructorHostFnContext] };

/**
 * Authorization context of a single contract call.
 *
 * This struct corresponds to a `require_auth_for_args` call for an address
 * from `contract` function with `fn_name` name and `args` arguments.
 */
export interface ContractContext {
  args: Array<any>;
  contract: string;
  fn_name: string;
}

/**
 * Authorization context for `create_contract` host function that creates a
 * new contract on behalf of authorizer address.
 */
export interface CreateContractHostFnContext {
  executable: ContractExecutable;
  salt: Buffer;
}

/**
 * Authorization context for `create_contract` host function that creates a
 * new contract on behalf of authorizer address.
 * This is the same as `CreateContractHostFnContext`, but also has
 * contract constructor arguments.
 */
export interface CreateContractWithConstructorHostFnContext {
  constructor_args: Array<any>;
  executable: ContractExecutable;
  salt: Buffer;
}

/**
 * Represents different types of signers in the smart account system.
 */
 export type Signer =
  /**
   * A delegated signer, any contract or account address, authenticated
   * through `require_auth_for_args((preimage,))`. Transaction simulation
   * does not return this nested authorization entry, because the call
   * happens inside `__check_auth`. Clients add it manually: an entry for
   * the delegated address whose root invocation is `__check_auth` on the
   * smart account with the [`AuthDigestPreimage`] as its single argument.
   * See `src/smart_account/test/auth_entries.rs` for a reference
   * construction.
   */
  { tag: "Delegated"; values: readonly [string] } |
  /**
   * An external signer with custom verification logic.
   * Contains the verifier contract address and the public key data.
   */
  { tag: "External"; values: readonly [string, Buffer] };

/**
 * A complete context rule defining authorization requirements.
 */
export interface ContextRule {
  /**
   * The type of context this rule applies to.
   */
  context_type: ContextRuleType;
  /**
   * Unique identifier for the context rule.
   */
  id: number;
  /**
   * Human-readable name for the context rule.
   */
  name: string;
  /**
   * List of policy contracts that must be satisfied.
   */
  policies: Array<string>;
  /**
   * Global registry IDs for each policy, positionally aligned with
   * `policies`.
   */
  policy_ids: Array<number>;
  /**
   * Global registry IDs for each signer, positionally aligned with
   * `signers`.
   */
  signer_ids: Array<number>;
  /**
   * List of signers authorized by this rule.
   */
  signers: Array<Signer>;
  /**
   * Optional expiration ledger sequence for the rule.
   */
  valid_until: number | null;
}

/**
 * Types of contexts that can be authorized by smart account rules.
 */
 export type ContextRuleType =
  /**
   * Default rules that can authorize any context.
   */
  { tag: "Default"; values: void } |
  /**
   * Rules specific to calling a particular contract.
   */
  { tag: "CallContract"; values: readonly [string] } |
  /**
   * Rules specific to creating a contract with a particular WASM hash.
   */
  { tag: "CreateContract"; values: readonly [Buffer] } |
  /**
   * Rules specific to creating a contract from the executable reference that
   * `owner` stores under `tag`.
   */
  { tag: "CreateContractExternalRef"; values: readonly [string, string] };
    export type ContractEvent = InstalledEvent | UninstalledEvent;
    

export type TrustPolicyError = (typeof TrustPolicyError)[keyof typeof TrustPolicyError];
