// Generated by scripts/gen-clients.mjs from scope_webauthn_verifier.wasm (sha256 cd1add1c65f781c30e79ac02c8f22489f06ba14d04e549615beec8b8f39ad5c7).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = 'cd1add1c65f781c30e79ac02c8f22489f06ba14d04e549615beec8b8f39ad5c7';
