// Generated by scripts/gen-clients.mjs from scope_webauthn_verifier.wasm (sha256 cd1add1c65f781c30e79ac02c8f22489f06ba14d04e549615beec8b8f39ad5c7).
// Do not edit: rebuild the contract and run the script again.


    /**
 * Error types for WebAuthn verification operations.
 */
export const WebAuthnError = {
  /**
   * The signature payload is invalid or has incorrect format.
   */
  3110 : { message: "SignaturePayloadInvalid" },
  /**
   * The client data exceeds the maximum allowed length.
   */
  3111 : { message: "ClientDataTooLong" },
  /**
   * Failed to parse JSON from client data.
   */
  3112 : { message: "JsonParseError" },
  /**
   * The type field in client data is not "webauthn.get".
   */
  3113 : { message: "TypeFieldInvalid" },
  /**
   * The challenge in client data does not match expected value.
   */
  3114 : { message: "ChallengeInvalid" },
  /**
   * The authenticator data format is invalid or too short.
   */
  3115 : { message: "AuthDataFormatInvalid" },
  /**
   * The User Present (UP) bit is not set in authenticator flags.
   */
  3116 : { message: "PresentBitNotSet" },
  /**
   * The User Verified (UV) bit is not set in authenticator flags.
   */
  3117 : { message: "VerifiedBitNotSet" },
  /**
   * Invalid relationship between Backup Eligibility and State bits.
   */
  3118 : { message: "BackupEligibilityAndStateNotSet" },
  /**
   * The provided key data does not contain a valid 65-byte public key.
   */
  3119 : { message: "KeyDataInvalid" }
}
    
    

export type WebAuthnError = (typeof WebAuthnError)[keyof typeof WebAuthnError];
