// Generated by scripts/gen-clients.mjs from scope_ed25519_verifier.wasm (sha256 f0113a9bcf90468e5e8ef8a32556843e815ca32ff0dd56837328424811f0136b).
// Do not edit: rebuild the contract and run the script again.
import {Spec, AssembledTransaction, Client as ContractClient, ClientOptions as ContractClientOptions, MethodOptions, ExternalExecutableRef} from '@stellar/stellar-sdk/contract';
import { Buffer } from 'buffer';

export interface Client {
  verify({ signature_payload, key_data, sig_data }: { signature_payload: Buffer; key_data: Buffer; sig_data: Buffer }, options?: MethodOptions): Promise<AssembledTransaction<boolean>>;
  canonicalize_key({ key_data }: { key_data: Buffer }, options?: MethodOptions): Promise<AssembledTransaction<Buffer>>;
  batch_canonicalize_key({ keys_data }: { keys_data: Array<Buffer> }, options?: MethodOptions): Promise<AssembledTransaction<Array<Buffer>>>;
}

export class Client extends ContractClient {
  constructor(public readonly options: ContractClientOptions) {
    super(
      new Spec(["AAAAAAAAAAAAAAAGdmVyaWZ5AAAAAAADAAAAAAAAABFzaWduYXR1cmVfcGF5bG9hZAAAAAAAAA4AAAAAAAAACGtleV9kYXRhAAAD7gAAACAAAAAAAAAACHNpZ19kYXRhAAAD7gAAAEAAAAABAAAAAQ==", "AAAAAAAAAAAAAAAQY2Fub25pY2FsaXplX2tleQAAAAEAAAAAAAAACGtleV9kYXRhAAAD7gAAACAAAAABAAAADg==", "AAAAAAAAAAAAAAAWYmF0Y2hfY2Fub25pY2FsaXplX2tleQAAAAAAAQAAAAAAAAAJa2V5c19kYXRhAAAAAAAD6gAAA+4AAAAgAAAAAQAAA+oAAAAO"]),
      options
    );
  }

   static deploy<T = Client>(options: MethodOptions & Omit<ContractClientOptions, 'contractId'> & { salt?: Buffer | Uint8Array; address?: string; } & ({ wasmHash: Buffer | string; format?: "hex" | "base64"; externalRef?: never; } | { externalRef: ExternalExecutableRef; wasmHash?: never; format?: never; })): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy(null, options);
  }
  public readonly fromJSON = {
    verify : this.txFromJSON<boolean>,  canonicalize_key : this.txFromJSON<Buffer>,  batch_canonicalize_key : this.txFromJSON<Array<Buffer>>
  };

}