// Generated by scripts/gen-clients.mjs from scope_ed25519_verifier.wasm (sha256 f0113a9bcf90468e5e8ef8a32556843e815ca32ff0dd56837328424811f0136b).
// Do not edit: rebuild the contract and run the script again.


    
    
    