// Generated by scripts/gen-clients.mjs from scope_attestations.wasm (sha256 8e4cdff50b302da02eb3a120f4749603d3fad217d1be08c77f346f68abf33df4).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = '8e4cdff50b302da02eb3a120f4749603d3fad217d1be08c77f346f68abf33df4';
