// Generated by scripts/gen-clients.mjs from scope_attestations.wasm (sha256 8e4cdff50b302da02eb3a120f4749603d3fad217d1be08c77f346f68abf33df4).
// Do not edit: rebuild the contract and run the script again.
import {Address} from '@stellar/stellar-sdk';
import { Buffer } from 'buffer';

    /**
 * Error Enum: Error
 */
export const Error = {
  /**
   * Score above 100, more delivered calls or receipts than calls.
   */
  1 : { message: "InvalidAttestation" },
  /**
   * `expires_ledger` is not in the future.
   */
  2 : { message: "AlreadyExpired" },
  3 : { message: "NotFound" },
  /**
   * The new attestation is older than the one stored.
   */
  4 : { message: "Stale" },
  /**
   * Bond below the configured minimum.
   */
  5 : { message: "BondTooLow" },
  /**
   * The attester is not registered or not active.
   */
  6 : { message: "NotAttester" },
  /**
   * Unbonding has not started or the waiting period has not passed.
   */
  7 : { message: "StillBonded" },
  8 : { message: "InvalidAmount" },
  9 : { message: "ProofTooLong" }
}

/**
 * Struct: Config
 */
export interface Config {
  /**
   * SEP-41 token used for bonds (USDC on mainnet).
   */
  bond_token: string;
  min_bond: bigint;
  /**
   * Ledgers between `start_unbond` and `withdraw`, so a bad attestation
   * can still be slashed after the attester leaves.
   */
  unbond_ledgers: number;
}

/**
 * Event: Slashed
 */
export interface SlashedEvent {
  name: "Slashed";
  data: {
    attester: string;
    amount?: bigint;
    to?: string;
  };
}

/**
 * Event: Attested
 */
export interface AttestedEvent {
  name: "Attested";
  data: {
    attester: string;
    key: Buffer;
    score?: number;
    expires_ledger?: number;
  };
}

/**
 * Event: Unbonding
 */
export interface UnbondingEvent {
  name: "Unbonding";
  data: {
    attester: string;
    unbond_at?: number;
  };
}

/**
 * Event: Withdrawn
 */
export interface WithdrawnEvent {
  name: "Withdrawn";
  data: {
    attester: string;
    amount?: bigint;
  };
}

/**
 * Event: Registered
 */
export interface RegisteredEvent {
  name: "Registered";
  data: {
    attester: string;
    bond?: bigint;
  };
}

/**
 * Attestation for one endpoint (payTo + URL).
 */
export interface Attestation {
  calls: number;
  delivered: number;
  /**
   * Merkle root of the evidence (see docs/evidence.md).
   */
  evidence: Buffer;
  expires_ledger: number;
  measured_at: bigint;
  method: number;
  p50_ms: number;
  price_ok: boolean;
  score: number;
}

/**
 * Struct: AttesterInfo
 */
export interface AttesterInfo {
  active: boolean;
  bond: bigint;
  /**
   * Ledger from which the bond can be withdrawn; 0 while bonded.
   */
  unbond_at: number;
}

/**
 * Event: SellerAttested
 */
export interface SellerAttestedEvent {
  name: "SellerAttested";
  data: {
    attester: string;
    seller: string;
    score?: number;
    expires_ledger?: number;
  };
}

/**
 * Attestation for a seller's payment address, across its endpoints.
 */
export interface SellerAttestation {
  calls: number;
  delivered: number;
  endpoints: number;
  evidence: Buffer;
  expires_ledger: number;
  measured_at: bigint;
  method: number;
  /**
   * Paid calls that came with a valid seller-signed delivery receipt.
   */
  receipts: number;
  score: number;
}
    export type ContractEvent = SlashedEvent | AttestedEvent | UnbondingEvent | WithdrawnEvent | RegisteredEvent | SellerAttestedEvent;
    

export type Error = (typeof Error)[keyof typeof Error];
