// Generated by scripts/gen-clients.mjs. Typed clients for the 402Scope contracts.
/** Attestation registry: bonded attesters, seller scores, evidence roots. */
export * as attestations from './attestations/index.js';
/** Trust policy for OpenZeppelin smart accounts: refuse payments to sellers below a score. */
export * as trustPolicy from './trustPolicy/index.js';
/** Agent wallet: an OpenZeppelin smart account with the trust policy installed. */
export * as agentWallet from './agentWallet/index.js';
/** Ed25519 verifier for the smart account signers. */
export * as ed25519Verifier from './ed25519Verifier/index.js';
/** Spending limit policy: at most an amount per rolling window, x402-compatible. */
export * as spendingLimit from './spendingLimit/index.js';
/** WebAuthn (passkey) verifier for smart account signers. */
export * as webauthnVerifier from './webauthnVerifier/index.js';
