// Generated by scripts/gen-clients.mjs from scope_refund_bond.wasm (sha256 e54cb4c5bc28d8aa783c99bee21a21d388b0e3fb2cae383030e13298ac2eada3).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = 'e54cb4c5bc28d8aa783c99bee21a21d388b0e3fb2cae383030e13298ac2eada3';
