// Generated by scripts/gen-clients.mjs from scope_refund_bond.wasm (sha256 e54cb4c5bc28d8aa783c99bee21a21d388b0e3fb2cae383030e13298ac2eada3).
// Do not edit: rebuild the contract and run the script again.
import {Address} from '@stellar/stellar-sdk';
import { Buffer } from 'buffer';

    /**
 * Struct: Bond
 */
export interface Bond {
  balance: bigint;
  owner: string;
  /**
   * Amount the owner asked to withdraw, and from which ledger it may.
   */
  pending: bigint;
  unlock_ledger: number;
}

/**
 * Struct: Claim
 */
export interface Claim {
  /**
   * The seller's ed25519 public key (the receipt's signer).
   */
  key: Buffer;
  receipt: Receipt;
  signature: Buffer;
}

/**
 * Struct: Config
 */
export interface Config {
  /**
   * Seconds after the receipt during which a refund can be claimed.
   */
  claim_window: bigint;
  /**
   * Ledgers between asking to withdraw and withdrawing.
   */
  notice_ledgers: number;
}

/**
 * Enum: Outcome
 */
export enum Outcome {
  /**
   * Enum Case: Refunded
   */
  Refunded = 0,
  /**
   * The bond did not cover the whole amount; what it held was refunded.
   */
  PartlyRefunded = 1,
  /**
   * Enum Case: AlreadyClaimed
   */
  AlreadyClaimed = 2,
  /**
   * The receipt shows no breach of the seller's own terms.
   */
  NoBreach = 3,
  /**
   * Outside the claim window.
   */
  Expired = 4,
  /**
   * No bond, or an empty one, for this key and token.
   */
  NoBond = 5
}

/**
 * What the seller signs for one paid response. A Soroban struct, so the
 * contract and any SDK compute the same XDR and the same hash.
 */
export interface Receipt {
  /**
   * Age of the data, as the seller declared it, in seconds (NO_AGE if not declared).
   */
  age: number;
  amount: bigint;
  /**
   * SEP-41 token paid.
   */
  asset: string;
  /**
   * Unix seconds when the seller signed.
   */
  at: bigint;
  /**
   * sha256 of the response body.
   */
  body: Buffer;
  /**
   * sha256 of the X-402-Declaration header (zeros if none).
   */
  decl: Buffer;
  /**
   * Maximum age the seller promised in its terms (0 if none).
   */
  max_age: number;
  pay_to: string;
  payer: string;
  /**
   * sha256 of the PAYMENT-SIGNATURE header: identifies the payment.
   */
  payment: Buffer;
  /**
   * sha256 of the resource URL.
   */
  resource: Buffer;
  /**
   * The seller declared this response unusable (or not established when its terms require it).
   */
  unusable: boolean;
}

/**
 * Event: Refunded
 */
export interface RefundedEvent {
  name: "Refunded";
  data: {
    key: Buffer;
    payer: string;
    payment?: Buffer;
    token?: string;
    amount?: bigint;
  };
}

/**
 * Error Enum: BondError
 */
export const BondError = {
  1 : { message: "InvalidAmount" },
  /**
   * This signing key's bond in this token belongs to another owner.
   */
  2 : { message: "KeyTaken" },
  3 : { message: "NoBond" },
  4 : { message: "NothingToWithdraw" },
  /**
   * The notice period has not passed yet.
   */
  5 : { message: "StillLocked" },
  6 : { message: "BatchTooLarge" }
}

/**
 * Event: Deposited
 */
export interface DepositedEvent {
  name: "Deposited";
  data: {
    key: Buffer;
    token?: string;
    owner?: string;
    balance?: bigint;
  };
}

/**
 * Event: Withdrawn
 */
export interface WithdrawnEvent {
  name: "Withdrawn";
  data: {
    key: Buffer;
    token?: string;
    amount?: bigint;
  };
}

/**
 * Event: WithdrawRequested
 */
export interface WithdrawRequestedEvent {
  name: "WithdrawRequested";
  data: {
    key: Buffer;
    token?: string;
    amount?: bigint;
    unlock_ledger?: number;
  };
}
    export type ContractEvent = RefundedEvent | DepositedEvent | WithdrawnEvent | WithdrawRequestedEvent;
    

export type BondError = (typeof BondError)[keyof typeof BondError];
