#!/usr/bin/env node
// Generates typed TypeScript clients for the 402Scope contracts from their
// built wasm, with the Stellar JS SDK's binding generator (the same code as
// `npx stellar-js generate`). Output goes to src/clients/<name>/ and is
// compiled and exported with the package, so callers get typed methods and
// types for every contract instead of hand-built ScVals.
//
// Usage: node scripts/gen-clients.mjs <wasm-dir>
// CI runs it after `stellar contract build`; the result is committed.

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BindingGenerator } from '@stellar/stellar-sdk';

const CONTRACTS = [
  // [module name, wasm file, what it is]
  ['attestations', 'scope_attestations.wasm', 'Attestation registry: bonded attesters, seller scores, evidence roots'],
  ['trustPolicy', 'scope_trust_policy.wasm', 'Trust policy for OpenZeppelin smart accounts: refuse payments to sellers below a score'],
  ['agentWallet', 'scope_agent_wallet.wasm', 'Agent wallet: an OpenZeppelin smart account with the trust policy installed'],
  ['ed25519Verifier', 'scope_ed25519_verifier.wasm', 'Ed25519 verifier for the smart account signers'],
  ['spendingLimit', 'scope_spending_limit.wasm', 'Spending limit policy: at most an amount per rolling window, x402-compatible'],
  ['webauthnVerifier', 'scope_webauthn_verifier.wasm', 'WebAuthn (passkey) verifier for smart account signers'],
];

const wasmDir = process.argv[2];
if (!wasmDir) {
  console.error('usage: node scripts/gen-clients.mjs <wasm-dir>');
  process.exit(2);
}
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'src', 'clients');
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

const header = (name, wasm, hash) =>
  `// Generated by scripts/gen-clients.mjs from ${wasm} (sha256 ${hash}).\n// Do not edit: rebuild the contract and run the script again.\n`;

const done = [];
for (const [name, file, about] of CONTRACTS) {
  const path = join(wasmDir, file);
  if (!existsSync(path)) {
    console.error(`missing ${path}`);
    process.exit(1);
  }
  const wasm = readFileSync(path);
  const hash = createHash('sha256').update(wasm).digest('hex');
  const gen = await BindingGenerator.fromWasm(wasm);
  const b = gen.generate({ contractName: file.replace(/\.wasm$/, '').replace(/_/g, '-') });
  const dir = join(out, name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'client.ts'), header(name, file, hash) + b.client);
  // The generator emits contract errors as const objects but uses their names as
  // types in Result<T, E>; give each one a matching type (value and type names
  // can coexist in TypeScript).
  const errorTypes = [...b.types.matchAll(/^export const (\w+) = \{/gm)]
    .map(([, n]) => `export type ${n} = (typeof ${n})[keyof typeof ${n}];`)
    .join('\n');
  writeFileSync(join(dir, 'types.ts'), header(name, file, hash) + b.types + (errorTypes ? `\n\n${errorTypes}\n` : ''));
  writeFileSync(join(dir, 'index.ts'), header(name, file, hash) + b.index + `\nexport const WASM_SHA256 = '${hash}';\n`);
  done.push({ name, about, hash });
  console.log(`${name}: ${file} ${hash}`);
}

writeFileSync(
  join(out, 'index.ts'),
  `// Generated by scripts/gen-clients.mjs. Typed clients for the 402Scope contracts.\n` +
    done.map((d) => `/** ${d.about}. */\nexport * as ${d.name} from './${d.name}/index.js';`).join('\n') +
    '\n',
);
