// Generated by scripts/gen-clients.mjs from scope_spending_limit.wasm (sha256 27333171e8f72dae45c9c107c9aa2e4c74aef29f709aed964160f518d1caf0a3).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = '27333171e8f72dae45c9c107c9aa2e4c74aef29f709aed964160f518d1caf0a3';
