// Generated by scripts/gen-clients.mjs from scope_escrow.wasm (sha256 a654039322ea7be968cd273de01f0d00bdc0883a7d3fbada22c5ee12d1898b5e).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = 'a654039322ea7be968cd273de01f0d00bdc0883a7d3fbada22c5ee12d1898b5e';
