// Generated by scripts/gen-clients.mjs from scope_escrow.wasm (sha256 a654039322ea7be968cd273de01f0d00bdc0883a7d3fbada22c5ee12d1898b5e).
// Do not edit: rebuild the contract and run the script again.
import {Address} from '@stellar/stellar-sdk';
import { Buffer } from 'buffer';

    /**
 * Struct: Hold
 */
export interface Hold {
  amount: bigint;
  asset: string;
  /**
   * Unix seconds when paid.
   */
  paid_at: bigint;
  payer: string;
  /**
   * Unix seconds after which a delivered payment can be released.
   */
  release_at: bigint;
  seller: string;
  status: Status;
}

/**
 * Event: Paid
 */
export interface PaidEvent {
  name: "Paid";
  data: {
    id: Buffer;
    payer?: string;
    seller?: string;
    asset?: string;
    amount?: bigint;
  };
}

/**
 * Struct: Config
 */
export interface Config {
  /**
   * Refund bond contract whose bonds let sellers be paid at once.
   */
  bond_contract: string | null;
  /**
   * Seconds a posted receipt can be contested before release (sellers without a covering bond).
   */
  contest_window: bigint;
  /**
   * Seconds the seller has to post a receipt before the payer can be refunded.
   */
  receipt_deadline: bigint;
}

/**
 * Enum: Status
 */
export enum Status {
  /**
   * Enum Case: Held
   */
  Held = 0,
  /**
   * The seller posted a receipt with no breach; released after `release_at`.
   */
  Delivered = 1,
  /**
   * Enum Case: Released
   */
  Released = 2,
  /**
   * Enum Case: Refunded
   */
  Refunded = 3
}

/**
 * Same struct as the refund bond's: one signature is valid in both contracts.
 */
export interface Receipt {
  age: number;
  amount: bigint;
  asset: string;
  at: bigint;
  body: Buffer;
  decl: Buffer;
  max_age: number;
  pay_to: string;
  payer: string;
  /**
   * For escrow payments: the escrow id.
   */
  payment: Buffer;
  resource: Buffer;
  unusable: boolean;
}

/**
 * Event: Refunded
 */
export interface RefundedEvent {
  name: "Refunded";
  data: {
    id: Buffer;
    payer?: string;
    amount?: bigint;
    /**
     * 0 a receipt showed a breach, 1 no receipt by the deadline.
     */
    why?: number;
  };
}

/**
 * Event: Released
 */
export interface ReleasedEvent {
  name: "Released";
  data: {
    id: Buffer;
    seller?: string;
    amount?: bigint;
    /**
     * 0 confirmed by the payer, 1 bonded seller's receipt, 2 after the contest window.
     */
    how?: number;
  };
}

/**
 * Event: Delivered
 */
export interface DeliveredEvent {
  name: "Delivered";
  data: {
    id: Buffer;
    release_at?: bigint;
  };
}

/**
 * Error Enum: EscrowError
 */
export const EscrowError = {
  1 : { message: "InvalidAmount" },
  /**
   * A payment with this id already exists.
   */
  2 : { message: "Exists" },
  3 : { message: "NotFound" },
  /**
   * The payment is already released or refunded.
   */
  4 : { message: "Closed" },
  /**
   * The receipt is for another payment, payer, seller, token or amount.
   */
  5 : { message: "WrongReceipt" },
  /**
   * The receipt is not signed by the seller's key.
   */
  6 : { message: "WrongSigner" },
  /**
   * Too early: the deadline or the contest window has not passed.
   */
  7 : { message: "TooEarly" },
  8 : { message: "BatchTooLarge" }
}
    export type ContractEvent = PaidEvent | RefundedEvent | ReleasedEvent | DeliveredEvent;
    

export type EscrowError = (typeof EscrowError)[keyof typeof EscrowError];
