// Generated by scripts/gen-clients.mjs from scope_agent_wallet.wasm (sha256 91c9885897457c644676e58a0038766e351b2dcf17674c0dba7ce9aebe9d7e29).
// Do not edit: rebuild the contract and run the script again.
export { Client } from "./client.js";
export * from "./types.js";
export const WASM_SHA256 = '91c9885897457c644676e58a0038766e351b2dcf17674c0dba7ce9aebe9d7e29';
